CREATE ROLE eva WITH PASSWORD 'axiom';
GRANT ALL PRIVILEGES ON DATABASE advertstat TO eva;

CREATE ROLE walle WITH LOGIN PASSWORD 'StupidWh33l';

CREATE SCHEMA adv_data;

GRANT USAGE ON SCHEMA adv_data TO walle;
